
# This is a message to hold data for speed


Header header

float64 speed 		# Speed of the wheelchair in meter/sec
float64 angle_vel	# Rotational velocity in rad/sec



#Standard metadata for higher-level flow data types
#sequence ID: consecutively increasing ID
#uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
#time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
#string frame_id

